# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
---

blank_issues_enabled: false

contact_links:
  - name: GitHub Community Support
    url: https://github.com/Beltiston/Chronos/discussions
    about: Please ask and answer questions here.

  - name: Report a vulnerability
    url: https://github.com/Beltiston/Chronos/security/advisories/new
    about: Please report security vulnerabilities here.
